-- SANABIL MESSAGES - MOCK VERIFICATION SETUP
-- Run this in the SQL Editor of your Supabase Dashboard

-- 1. Create the allowed_parents table (if it doesn't exist)
create table if not exists allowed_parents (
  id bigint generated by default as identity primary key,
  phone text unique not null,
  name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table allowed_parents enable row level security;

-- 3. Create a policy to allow anyone to READ (safely idempotent)
do $$
begin
  if not exists (
    select from pg_policies where policyname = 'Enable read access for all users' and tablename = 'allowed_parents'
  ) then
    create policy "Enable read access for all users" on allowed_parents for select using (true);
  end if;
end
$$;

-- 4. Insert Test Data (Uses ON CONFLICT to avoid duplicate error if you run it twice)
insert into allowed_parents (phone, name) values 
  ('+252634370911', 'Muuse Maxamed'),
  ('+252634458114', 'Test Parent'),
  ('+252634878112', 'Test Parent Two')
on conflict (phone) do nothing;
