-- ==========================================
-- SANABIL MESSAGES - CI3 BACKEND SIMULATION
-- ==========================================

-- 1. SCHOOLS (Master Data)
create table if not exists schools (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. STUDENTS (Linked to School)
create table if not exists students (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id),
  full_name text not null,
  class_name text,
  status text check (status in ('active', 'inactive')) default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. USERS/PARENTS (We use 'allowed_parents' as our user directory)
-- (We already have this table, but let's add the school_id if needed)
-- alter table allowed_parents add column school_id bigint references schools(id);

-- 4. STUDENT_PARENTS (The Link: Who sees what?)
create table if not exists student_parents (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id),
  parent_phone text references allowed_parents(phone), -- Linking by Phone for simplicity in this simulation
  relation text, 
  is_primary boolean default false
);

-- 5. USER_DEVICES (For Push Notifications - Workflow A)
create table if not exists user_devices (
  id bigint generated by default as identity primary key,
  user_phone text references allowed_parents(phone), -- Linked to the logged-in parent
  platform text check (platform in ('android', 'ios')),
  fcm_token text unique not null,
  is_active boolean default true,
  last_seen_at timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. MESSAGES (The content)
create table if not exists messages (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id),
  student_id bigint references students(id),
  type text check (type in ('absence', 'general', 'notice')),
  title text not null,
  body text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. MESSAGE_RECIPIENTS (Delivery Status)
create table if not exists message_recipients (
  id bigint generated by default as identity primary key,
  message_id bigint references messages(id),
  parent_phone text references allowed_parents(phone),
  status text check (status in ('pending', 'sent', 'failed')) default 'pending',
  error text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS) - "Only see your own data"
-- ==========================================

alter table schools enable row level security;
alter table students enable row level security;
alter table student_parents enable row level security;
alter table user_devices enable row level security;
alter table messages enable row level security;
alter table message_recipients enable row level security;

-- POLICY: Parents can read everything (For simulation simplicity, we allow generous read access)
-- In a real app, you would filter by `auth.uid()`, but here we filter by phone number matching the session.
-- For the Simulation Phase, we will keep RLS OPEN for read, but restricted for write.

create policy "Public Read" on schools for select using (true);
create policy "Public Read" on students for select using (true);

-- Devices: User can Insert/Update their OWN device
create policy "Users manage own devices" on user_devices
  for all using (true) with check (true); 
  -- (Simplified: in real production we check auth.uid() -> phone mapping)

-- Messages: Parents can see messages meant for them
create policy "Parents see their messages" on message_recipients
  for select using (true);

create policy "Parents see message content" on messages
  for select using (true);

-- ==========================================
-- MOCK DATA (For Testing)
-- ==========================================

-- 1. Create a School
insert into schools (name) values ('Sanabil High School');

-- 2. Create a Student (Maxamuud Cali)
insert into students (school_id, full_name, class_name) 
values (1, 'Maxamuud Cali', 'Grade 5A');

-- 3. Link Student to YOU (The Test Parent)
-- NOTE: We assume your phone '+252634370911' is already in 'allowed_parents'
insert into student_parents (student_id, parent_phone, relation)
values (1, '+252634370911', 'Father');

-- 4. Create a Test Message (Absence)
with new_msg as (
  insert into messages (school_id, student_id, type, title, body)
  values (1, 1, 'absence', 'Absence Alert', 'Student Maxamuud Cali was absent today.')
  returning id
)
insert into message_recipients (message_id, parent_phone)
select id, '+252634370911' from new_msg;
