-- Create OTP Queue for pending messages
CREATE TABLE IF NOT EXISTS public.otp_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone TEXT NOT NULL,
    code TEXT NOT NULL,
    status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create OTP Logs for history
CREATE TABLE IF NOT EXISTS public.otp_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone TEXT NOT NULL,
    status TEXT NOT NULL,
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS Policies
ALTER TABLE public.otp_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.otp_logs ENABLE ROW LEVEL SECURITY;

-- Only Service Role (Edge Functions & Python Script) can access these
CREATE POLICY "Service Role Full Access Queue" ON public.otp_queue
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Service Role Full Access Logs" ON public.otp_logs
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_otp_queue_status ON public.otp_queue(status);
-- LEGACY REFERENCE: not part of the deployable migration chain.
