-- Create a table to track sync status and errors
CREATE TABLE IF NOT EXISTS public.sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT REFERENCES public.schools(id),
    status TEXT CHECK (status IN ('SUCCESS', 'FAILED', 'PARTIAL')),
    message TEXT,
    details JSONB, -- Store full error object or stats (e.g., { "imported": 5, "failed": 0 })
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.sync_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Only service_role (Edge Functions) can insert logs
CREATE POLICY "Service Role can insert logs" ON public.sync_logs
    FOR INSERT
    TO service_role
    WITH CHECK (true);

-- Policy: Only admins (service_role) can view logs for now
CREATE POLICY "Service Role can view logs" ON public.sync_logs
    FOR SELECT
    TO service_role
    USING (true);

-- Grant access
GRANT ALL ON public.sync_logs TO service_role;
GRANT SELECT ON public.sync_logs TO authenticated; -- Maybe useful for dashboard later
-- LEGACY REFERENCE: not part of the deployable migration chain.
