BEGIN;

CREATE TABLE IF NOT EXISTS public.push_delivery_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expo_ticket_id TEXT NOT NULL UNIQUE,
  school_id BIGINT NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
  message_id BIGINT NOT NULL REFERENCES public.messages(id) ON DELETE CASCADE,
  user_device_id BIGINT NOT NULL REFERENCES public.user_devices(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'PENDING',
  error_code TEXT,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  receipt_checked_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT push_delivery_tickets_status_check
    CHECK (status IN ('PENDING', 'DELIVERED', 'FAILED'))
);

ALTER TABLE public.push_delivery_tickets ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.push_delivery_tickets FROM PUBLIC, anon, authenticated;
GRANT ALL PRIVILEGES ON TABLE public.push_delivery_tickets TO service_role;
REVOKE ALL ON SEQUENCE public.push_delivery_tickets_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.push_delivery_tickets_id_seq TO service_role;

CREATE INDEX IF NOT EXISTS push_delivery_tickets_pending_created_idx
  ON public.push_delivery_tickets (created_at, id)
  WHERE status = 'PENDING';

CREATE INDEX IF NOT EXISTS push_delivery_tickets_device_idx
  ON public.push_delivery_tickets (user_device_id, created_at DESC);

COMMIT;
