BEGIN;

-- Integration credentials, OTP secrets, and operational logs are server-only.
ALTER TABLE public.schools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.otp_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.otp_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_logs ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE public.schools FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.otp_queue FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.otp_logs FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.sync_logs FROM anon, authenticated;

GRANT ALL PRIVILEGES ON TABLE public.schools TO service_role;
GRANT ALL PRIVILEGES ON TABLE public.otp_queue TO service_role;
GRANT ALL PRIVILEGES ON TABLE public.otp_logs TO service_role;
GRANT ALL PRIVILEGES ON TABLE public.sync_logs TO service_role;

CREATE OR REPLACE FUNCTION public.scrub_terminal_otp_secret()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.status IN ('VERIFIED', 'FAILED') THEN
    NEW.code := '';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS scrub_terminal_otp_secret_trigger ON public.otp_queue;
CREATE TRIGGER scrub_terminal_otp_secret_trigger
BEFORE INSERT OR UPDATE OF status, code
ON public.otp_queue
FOR EACH ROW
EXECUTE FUNCTION public.scrub_terminal_otp_secret();

UPDATE public.otp_queue
SET code = ''
WHERE status IN ('VERIFIED', 'FAILED')
  AND code <> '';

-- Historical worker logs may contain the WhatsApp message body and OTP code.
UPDATE public.otp_logs
SET message = CASE
  WHEN status = 'SENT' THEN 'OTP delivered through WhatsApp.'
  WHEN status = 'VERIFIED' THEN 'OTP verified successfully.'
  WHEN status = 'FAILED' THEN 'OTP delivery or verification failed.'
  ELSE 'OTP operational event.'
END
WHERE message IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.otp_request_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id BIGINT NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
  phone_hash TEXT NOT NULL,
  ip_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT otp_request_attempts_phone_hash_check
    CHECK (phone_hash ~ '^[a-f0-9]{64}$'),
  CONSTRAINT otp_request_attempts_ip_hash_check
    CHECK (ip_hash ~ '^[a-f0-9]{64}$')
);

ALTER TABLE public.otp_request_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.otp_request_attempts FROM PUBLIC, anon, authenticated;
GRANT ALL PRIVILEGES ON TABLE public.otp_request_attempts TO service_role;
REVOKE ALL ON SEQUENCE public.otp_request_attempts_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.otp_request_attempts_id_seq TO service_role;

CREATE INDEX IF NOT EXISTS otp_request_attempts_school_phone_created_idx
  ON public.otp_request_attempts (school_id, phone_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS otp_request_attempts_school_ip_created_idx
  ON public.otp_request_attempts (school_id, ip_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS otp_request_attempts_created_idx
  ON public.otp_request_attempts (created_at);

CREATE OR REPLACE FUNCTION public.consume_otp_request_rate_limit(
  p_school_id BIGINT,
  p_phone_hash TEXT,
  p_ip_hash TEXT,
  p_window_seconds INTEGER DEFAULT 60,
  p_phone_limit INTEGER DEFAULT 3,
  p_ip_limit INTEGER DEFAULT 20
)
RETURNS TABLE (
  allowed BOOLEAN,
  retry_after_seconds INTEGER,
  phone_attempts INTEGER,
  ip_attempts INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  window_start TIMESTAMPTZ;
  phone_count INTEGER;
  ip_count INTEGER;
  oldest_phone_attempt TIMESTAMPTZ;
  oldest_ip_attempt TIMESTAMPTZ;
  retry_after INTEGER;
BEGIN
  IF auth.role() <> 'service_role' THEN
    RAISE EXCEPTION 'Service role required' USING ERRCODE = '42501';
  END IF;

  IF p_school_id IS NULL OR p_school_id <= 0
     OR COALESCE(p_phone_hash, '') !~ '^[a-f0-9]{64}$'
     OR COALESCE(p_ip_hash, '') !~ '^[a-f0-9]{64}$'
     OR p_window_seconds NOT BETWEEN 10 AND 3600
     OR p_phone_limit NOT BETWEEN 1 AND 20
     OR p_ip_limit NOT BETWEEN 1 AND 500 THEN
    RAISE EXCEPTION 'Invalid OTP rate-limit input';
  END IF;

  -- Serialize requests for the same school/IP and school/phone pair.
  PERFORM pg_advisory_xact_lock(hashtextextended(p_school_id::TEXT || ':ip:' || p_ip_hash, 0));
  PERFORM pg_advisory_xact_lock(hashtextextended(p_school_id::TEXT || ':phone:' || p_phone_hash, 0));

  window_start := NOW() - make_interval(secs => p_window_seconds);

  SELECT COUNT(*)::INTEGER, MIN(created_at)
  INTO ip_count, oldest_ip_attempt
  FROM public.otp_request_attempts
  WHERE school_id = p_school_id
    AND ip_hash = p_ip_hash
    AND created_at >= window_start;

  SELECT COUNT(*)::INTEGER, MIN(created_at)
  INTO phone_count, oldest_phone_attempt
  FROM public.otp_request_attempts
  WHERE school_id = p_school_id
    AND phone_hash = p_phone_hash
    AND created_at >= window_start;

  IF phone_count >= p_phone_limit OR ip_count >= p_ip_limit THEN
    retry_after := 1;
    IF phone_count >= p_phone_limit THEN
      retry_after := GREATEST(
        retry_after,
        CEIL(EXTRACT(EPOCH FROM (
          COALESCE(oldest_phone_attempt, NOW())
          + make_interval(secs => p_window_seconds)
          - NOW()
        )))::INTEGER
      );
    END IF;
    IF ip_count >= p_ip_limit THEN
      retry_after := GREATEST(
        retry_after,
        CEIL(EXTRACT(EPOCH FROM (
          COALESCE(oldest_ip_attempt, NOW())
          + make_interval(secs => p_window_seconds)
          - NOW()
        )))::INTEGER
      );
    END IF;

    RETURN QUERY SELECT
      FALSE,
      retry_after,
      phone_count,
      ip_count;
    RETURN;
  END IF;

  INSERT INTO public.otp_request_attempts (school_id, phone_hash, ip_hash)
  VALUES (p_school_id, p_phone_hash, p_ip_hash);

  -- The table is deliberately short-lived and contains hashes only.
  DELETE FROM public.otp_request_attempts
  WHERE created_at < NOW() - INTERVAL '24 hours';

  RETURN QUERY SELECT TRUE, 0, phone_count + 1, ip_count + 1;
END;
$$;

CREATE OR REPLACE FUNCTION public.enroll_verified_device(
  p_school_id BIGINT,
  p_phone TEXT,
  p_device_id TEXT,
  p_device_name TEXT DEFAULT NULL,
  p_platform TEXT DEFAULT NULL,
  p_app_variant TEXT DEFAULT NULL
)
RETURNS TABLE (
  id BIGINT,
  school_id BIGINT,
  phone_number TEXT,
  device_id TEXT,
  is_active BOOLEAN,
  trusted_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  last_seen_at TIMESTAMPTZ,
  last_login_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  clean_phone TEXT := public.normalize_somali_phone_sql(p_phone);
  clean_device_id TEXT := trim(COALESCE(p_device_id, ''));
  now_ts TIMESTAMPTZ := NOW();
BEGIN
  IF auth.role() <> 'service_role' THEN
    RAISE EXCEPTION 'Service role required' USING ERRCODE = '42501';
  END IF;

  IF clean_device_id !~ '^[A-Za-z0-9._:-]{8,160}$' THEN
    RAISE EXCEPTION 'Invalid device ID';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.allowed_parents ap
    JOIN public.schools s ON s.id = ap.school_id
    WHERE ap.school_id = p_school_id
      AND ap.phone_number = clean_phone
      AND COALESCE(ap.is_active, FALSE)
      AND COALESCE(s.is_active, FALSE)
  ) THEN
    RAISE EXCEPTION 'Parent is not active in this school' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  INSERT INTO public.user_devices AS existing (
    school_id,
    phone_number,
    device_id,
    device_name,
    platform,
    app_variant,
    is_active,
    trusted_at,
    revoked_at,
    last_seen_at,
    last_login_at,
    updated_at
  )
  VALUES (
    p_school_id,
    clean_phone,
    clean_device_id,
    NULLIF(trim(COALESCE(p_device_name, '')), ''),
    NULLIF(trim(COALESCE(p_platform, '')), ''),
    NULLIF(trim(COALESCE(p_app_variant, '')), ''),
    TRUE,
    now_ts,
    NULL,
    now_ts,
    now_ts,
    now_ts
  )
  ON CONFLICT (school_id, phone_number, device_id)
  DO UPDATE SET
    device_name = COALESCE(EXCLUDED.device_name, existing.device_name),
    platform = COALESCE(EXCLUDED.platform, existing.platform),
    app_variant = COALESCE(EXCLUDED.app_variant, existing.app_variant),
    is_active = TRUE,
    trusted_at = now_ts,
    revoked_at = NULL,
    last_seen_at = now_ts,
    last_login_at = now_ts,
    updated_at = now_ts
  RETURNING
    existing.id,
    existing.school_id,
    existing.phone_number,
    existing.device_id,
    existing.is_active,
    existing.trusted_at,
    existing.revoked_at,
    existing.last_seen_at,
    existing.last_login_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.touch_my_device(
  p_school_id BIGINT,
  p_device_id TEXT,
  p_device_name TEXT DEFAULT NULL,
  p_platform TEXT DEFAULT NULL,
  p_fcm_token TEXT DEFAULT NULL,
  p_app_variant TEXT DEFAULT NULL
)
RETURNS TABLE (
  id BIGINT,
  school_id BIGINT,
  phone_number TEXT,
  device_id TEXT,
  is_active BOOLEAN,
  trusted_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  last_seen_at TIMESTAMPTZ,
  last_login_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  clean_phone TEXT;
  clean_device_id TEXT := trim(COALESCE(p_device_id, ''));
BEGIN
  IF NOT public.parent_has_school_access(p_school_id) THEN
    RAISE EXCEPTION 'Parent is not active in this school' USING ERRCODE = '42501';
  END IF;

  IF clean_device_id !~ '^[A-Za-z0-9._:-]{8,160}$' THEN
    RAISE EXCEPTION 'Invalid device ID';
  END IF;

  clean_phone := public.current_parent_phone();

  RETURN QUERY
  UPDATE public.user_devices AS existing
  SET
    device_name = COALESCE(NULLIF(trim(COALESCE(p_device_name, '')), ''), existing.device_name),
    platform = COALESCE(NULLIF(trim(COALESCE(p_platform, '')), ''), existing.platform),
    fcm_token = COALESCE(NULLIF(trim(COALESCE(p_fcm_token, '')), ''), existing.fcm_token),
    app_variant = COALESCE(NULLIF(trim(COALESCE(p_app_variant, '')), ''), existing.app_variant),
    last_seen_at = NOW(),
    updated_at = NOW()
  WHERE existing.school_id = p_school_id
    AND existing.phone_number = clean_phone
    AND existing.device_id = clean_device_id
    AND COALESCE(existing.is_active, FALSE)
    AND existing.revoked_at IS NULL
  RETURNING
    existing.id,
    existing.school_id,
    existing.phone_number,
    existing.device_id,
    existing.is_active,
    existing.trusted_at,
    existing.revoked_at,
    existing.last_seen_at,
    existing.last_login_at;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Device is not trusted. Complete OTP verification again.'
      USING ERRCODE = '42501';
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.consume_otp_request_rate_limit(BIGINT, TEXT, TEXT, INTEGER, INTEGER, INTEGER)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.enroll_verified_device(BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.touch_my_device(BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT)
  FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.consume_otp_request_rate_limit(BIGINT, TEXT, TEXT, INTEGER, INTEGER, INTEGER)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.enroll_verified_device(BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.touch_my_device(BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT)
  TO authenticated, service_role;

-- Both legacy overloads can create/reactivate a device without a fresh OTP.
-- Removing them also eliminates their known ambiguous-column runtime defects.
DROP FUNCTION IF EXISTS public.register_my_device(TEXT, TEXT, TEXT, TEXT, TEXT, BOOLEAN);
DROP FUNCTION IF EXISTS public.register_my_device(BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT, BOOLEAN);

COMMIT;
