BEGIN;

CREATE TABLE IF NOT EXISTS public.sync_log_cleanup_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_row_count BIGINT NOT NULL,
  first_log_at TIMESTAMPTZ,
  last_log_at TIMESTAMPTZ,
  status_counts JSONB NOT NULL DEFAULT '{}'::JSONB,
  reason TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sync_log_incident_samples (
  source_log_id BIGINT PRIMARY KEY,
  school_id BIGINT,
  status TEXT,
  message TEXT,
  details JSONB,
  source_created_at TIMESTAMPTZ,
  archived_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.sync_log_cleanup_audits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_log_incident_samples ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE public.sync_log_cleanup_audits FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.sync_log_incident_samples FROM anon, authenticated;

INSERT INTO public.sync_log_incident_samples (
  source_log_id,
  school_id,
  status,
  message,
  details,
  source_created_at
)
SELECT
  logs.id,
  logs.school_id,
  logs.status,
  logs.message,
  logs.details,
  logs.created_at
FROM public.sync_logs logs
WHERE logs.status IN ('FAILED', 'PARTIAL')
ORDER BY logs.id DESC
LIMIT 5000
ON CONFLICT (source_log_id) DO NOTHING;

INSERT INTO public.sync_log_cleanup_audits (
  source_row_count,
  first_log_at,
  last_log_at,
  status_counts,
  reason
)
SELECT
  COALESCE(SUM(grouped.row_count), 0),
  MIN(grouped.first_log_at),
  MAX(grouped.last_log_at),
  COALESCE(
    jsonb_object_agg(grouped.status, grouped.row_count)
      FILTER (WHERE grouped.status IS NOT NULL),
    '{}'::JSONB
  ),
  'Emergency recovery after duplicate bridge cron generated millions of per-message logs.'
FROM (
  SELECT
    COALESCE(status, 'NULL') AS status,
    COUNT(*) AS row_count,
    MIN(created_at) AS first_log_at,
    MAX(created_at) AS last_log_at
  FROM public.sync_logs
  GROUP BY COALESCE(status, 'NULL')
) grouped;

TRUNCATE TABLE public.sync_logs RESTART IDENTITY;

COMMIT;
