BEGIN;

CREATE TABLE IF NOT EXISTS public.operational_history_cleanup_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_table TEXT NOT NULL,
  source_row_count BIGINT NOT NULL,
  first_event_at TIMESTAMPTZ,
  last_event_at TIMESTAMPTZ,
  status_counts JSONB NOT NULL DEFAULT '{}'::JSONB,
  reason TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.operational_history_cleanup_audits ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES
  ON TABLE public.operational_history_cleanup_audits
  FROM anon, authenticated;

INSERT INTO public.operational_history_cleanup_audits (
  source_table,
  source_row_count,
  first_event_at,
  last_event_at,
  status_counts,
  reason
)
SELECT
  'cron.job_run_details',
  COALESCE(SUM(status_group.row_count), 0),
  MIN(start_time),
  MAX(end_time),
  COALESCE(
    jsonb_object_agg(status_group.status, status_group.row_count),
    '{}'::JSONB
  ),
  'Emergency recovery after duplicate bridge cron jobs exhausted database quota.'
FROM (
  SELECT
    COALESCE(status, 'NULL') AS status,
    COUNT(*) AS row_count,
    MIN(start_time) AS start_time,
    MAX(start_time) AS end_time
  FROM cron.job_run_details
  GROUP BY COALESCE(status, 'NULL')
) status_group;

INSERT INTO public.operational_history_cleanup_audits (
  source_table,
  source_row_count,
  first_event_at,
  last_event_at,
  status_counts,
  reason
)
SELECT
  'net._http_response',
  COALESCE(SUM(status_group.row_count), 0),
  MIN(created),
  MAX(last_created),
  COALESCE(
    jsonb_object_agg(status_group.status_code, status_group.row_count),
    '{}'::JSONB
  ),
  'Completed pg_net responses removed after audit; response bodies were not archived.'
FROM (
  SELECT
    COALESCE(status_code::TEXT, 'NULL') AS status_code,
    COUNT(*) AS row_count,
    MIN(created) AS created,
    MAX(created) AS last_created
  FROM net._http_response
  GROUP BY COALESCE(status_code::TEXT, 'NULL')
) status_group;

TRUNCATE TABLE cron.job_run_details;
TRUNCATE TABLE net._http_response;

COMMIT;
